export class ActionTypes {

    static FETCH_ADDRESS_LIST = 'FETCH_ADDRESS_LIST';
    static FETCH_ADDRESS_LIST_SUCCESS = 'FETCH_ADDRESS_LIST_SUCCESS';
    static FETCH_ADDRESS_LIST_ERROR = 'FETCH_ADDRESS_LIST_ERROR';
}